// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldaE-AK0rgjRxoSSfqGywz60VyXkHBk8',
    appId: '1:508250648779:web:c194175848b4a701daab4e',
    messagingSenderId: '508250648779',
    projectId: 'anuncios-domicilio-a5765',
    authDomain: 'anuncios-domicilio-a5765.firebaseapp.com',
    storageBucket: 'anuncios-domicilio-a5765.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4OmJmxzFg9dG8D52gfNReH4t5XxlWnYs',
    appId: '1:508250648779:android:d9cd109150b415cfdaab4e',
    messagingSenderId: '508250648779',
    projectId: 'anuncios-domicilio-a5765',
    storageBucket: 'anuncios-domicilio-a5765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyW7gLpKwPmzKSru76eq4hRK30rxtq_fQ',
    appId: '1:508250648779:ios:a9afa24025d7212bdaab4e',
    messagingSenderId: '508250648779',
    projectId: 'anuncios-domicilio-a5765',
    storageBucket: 'anuncios-domicilio-a5765.appspot.com',
    iosBundleId: 'com.example.anunciosDomicilio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyW7gLpKwPmzKSru76eq4hRK30rxtq_fQ',
    appId: '1:508250648779:ios:a9afa24025d7212bdaab4e',
    messagingSenderId: '508250648779',
    projectId: 'anuncios-domicilio-a5765',
    storageBucket: 'anuncios-domicilio-a5765.appspot.com',
    iosBundleId: 'com.example.anunciosDomicilio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBldaE-AK0rgjRxoSSfqGywz60VyXkHBk8',
    appId: '1:508250648779:web:cb1a44ac39e76867daab4e',
    messagingSenderId: '508250648779',
    projectId: 'anuncios-domicilio-a5765',
    authDomain: 'anuncios-domicilio-a5765.firebaseapp.com',
    storageBucket: 'anuncios-domicilio-a5765.appspot.com',
  );
}
